### PR TITLE
[1.2.8] Decrease countdown when full

### LINKED ISSUE #285: New lobby countdown system.
How about make new countdown system?
When the game entered 8 of 16 players to start the 120 sec countdown to start game. When lobby is full (16 of 16) start new countdown with 15 seconds to start if one player leave start new countdown with 40 sec to join new player.

### PR DESCRIPTION
**Pull request by sebastianbinder**
resolves #285 
adds config ``lobbytime-full``, checks if waiting game reaches max-players, then decreases countdown to ``lobbytime-full`` (if it isn't yet lower than this value)
adds message ``X more players needed.`` when player joins a waiting game, so people know how many players to wait for until countdown starts (depending on countdown start rule)

### CODE REVIEW

**Comment by sebastianbinder** [comment]
@Granik24 - wanna test it? :)

**Comment by Granik24** [comment]
@sebastianbinder Will test it soon. :)

**Comment by sebastianbinder** [comment]
Added @Granik24's CZ translation.

**Comment by Granik24** [comment]
@sebastianbinder Added all things, now, countdown is frozen in full arena.

**Comment by sebastianbinder** [comment]
@Granik24  ok. shit. I'll have a look on it.

**Comment by sebastianbinder** [comment]
@Granik24 
Actually I cannot reproduce this one. Just tested it the following ways:
Assuming you have a game with two teams with one player maximum each.
Scenario 1: Join the game with one player. Countdown starts running from 60. Join with the second player. Countdown decreases to 15 and runs further on.
Scenario 2: Join the game with one player. Countdown starts running from 60. Wait until countdown is lower than the value of ``lobbytime-full`` from config. Join with the second player. Countdown stays, because it was already lower than this value.

Did you test another scenario?

The only code snippet I added is the following (the rest is just code formatting):
```java
if (this.counter > this.lobbytimeWhenFull && this.game.getPlayerAmount() == this.game.getMaxPlayers()) {
  this.counter = this.lobbytimeWhenFull;
  this.game.broadcast(ChatColor.YELLOW + Main._l("lobby.countdown",ImmutableMap.of("sec", ChatColor.RED.toString() + this.counter + ChatColor.YELLOW)), players);
}
```
So in words "If the current countdown (``counter``) is higher than the ``lobbytimeWhenFull`` (``lobbytime-full`` from config) and if the current player amount is the same amount as the maximum player amount, then set the countdown to the value of ``lobbytime-full``.
You said it freezes the countdown. But then ``this.counter == this.lobbytimeWhenFull`` and my code doesn't apply anymore… So I don't know how this can happen.

**Comment by Granik24** [comment]
Well, I have game with two teams, one team, one player. 
If I join, nothing will happened, because game needs 2 players to start.
If second player joins to the game, It will start countdown with 45 seconds (yea, we have 45 seconds) and after that, your code will apply and countdown will be setted to 15 seconds. 
Then, countdown will freeze.

**Comment by sebastianbinder** [comment]
@Granik24, I just tried your scenario. Works perfectly here :(
I now rearranged the code a bit - hope this one works. It is now skipping the 45 to 15 decrease, it immediately starts with 15 in your scenario.

**Comment by Granik24** [comment]
@sebastianbinder, Will try it as soon as possible, now I'm not at home. Thanks for your help!

**Comment by Granik24** [comment]
@sebastianbinder Works great, good job. <3

**Comment by sebastianbinder** [comment]
@Granik24 yes!! :) Thank you <3

**Comment by sebastianbinder** [comment]
Just squashed all single commits into one commit https://github.com/sebastianbinder/bedwars-reloaded/commit/83ac0a6b1c649e1784d7dcf1c09720edc8dead6f

@Yannici – ready to merge if you like to :)

**Comment by Yannici** [comment]
Thanks a lot for your support, @sebastianbinder and @Granik24

**Comment by sebastianbinder** [comment]
You are very welcome @Yannici <3

**Comment by Granik24** [comment]
@Yannici For you, everytime. ;)

**Pull request merged**
