### PR TITLE
[1.2.8] Add bungeecord MOTD placeholders

### LINKED ISSUE #308: Question/Request: Placeholder for Game Name on Bungeecord MOTD
In einem BungeeCord-Setup läuft es ja in der Regel so, dass man mit Multiverse drauf eine Welt mit der Gamelobby hat und eine Welt mit dem Bedwars-Game. Letztlich ist doch eigentlich nur ein einziges Spiel auf dem Server drauf. Könnte man evtl. in folgendem Bereich der [Config](https://github.com/Yannici/bedwars-reloaded/blob/master/config.yml#L570)
```yml
bungeecord:
  motds:
    lobby: "&a[Lobby]"
    running: "&1[Running]"
    stopped: "&c[Stopped]"
    full: "&c[Full]"
```
einen Platzhalter für den Game-Namen einfügen, so wie es bei den [Schildern für "Nicht-Bungeecord"](https://github.com/Yannici/bedwars-reloaded/blob/master/config.yml#L881) möglich ist? Also damit bspw. folgendes möglich ist:
```yml
bungeecord:
  motds:
    lobby: |
      $regionname$
      &a[Lobby]
    running: |
      $regionname$
      &1[Running]
    stopped: |
      $regionname$
      &c[Stopped]
    full: |
      $regionname$
      &c[Full]
```
Angenommen ``regionname`` wäre ``Rush (2x4)`` dann käme das hier raus:
```yml
bungeecord:
  motds:
    lobby: |
      Rush (2x4)
      &7[&aLobby&7]
    running: |
      Rush (2x4)
      &1[Running]
    stopped: |
      Rush (2x4)
      [&cGestoppt&7]
    full: |
      Rush (2x4)
      &7[&cLobby&7]
```

Oder gibt es das schon irgendwie? Deswegen auch Question oder Request im Titel - denn kann ja sein, dass es schon irgendwo implementiert ist und nur in der [Config](https://github.com/Yannici/bedwars-reloaded/blob/master/config.yml#L570) nicht dokumentiert wurde.
Denn mein Plugin für die Teleport-Schilder kann bei der MOTD zwischen der ersten und der zweiten Zeile unterscheiden, sodass ich damit direkt den Game-Namen auf den Schildern auslesen könnte. Derzeit schreibe ich es händisch in jede Config, aber das ist ja nicht schön :)
Vielleicht wird da ja was draus :) Besten Dank und viele Grüße!

### PR DESCRIPTION
**Pull request by sebastianbinder**
resolves #308
to be honest: not really dry code, just copied and pasted existing methods.
locally tested, build on jenkins succeeded, tests in production on my server worked fine.

### CODE REVIEW

**Comment by Yannici** [comment]
@Granik24 could you maybe test that pull? Would be nice.

**Comment by Granik24** [comment]
@Yannici Will look in to it today. :)

**Comment by sebastianbinder** [comment]
@Yannici ja klar! Ist auch besser so, wenn es mal noch von anderer Seite getestet wird. Weil selbst entdeckt man einfach nie alle Fehler…

**Comment by Granik24** [comment]
@Yannici Tested, works as well. :)

**Comment by sebastianbinder** [comment]
Yeah :)

**Pull request merged**
