### PR TITLE
[1.2.8] Release

### LINKED ISSUE #233: Item-Frames can be broken by sheeps or blocks
Hello,
I have problem with TNT-Sheeps. Sheep can break item-frames, carpets and other blocks like this.
Can you please fix it? 
Thanks and have a good day :)

@sebastianbinder __schrieb zu diesem Thema:__
Hi. Ich habe auf meiner Map zu Dekozwecken Item Frames (halt diese Bilderrahmen inkl. Items "drin") platziert. Sinn davon ist natürlich nicht, dass die Spieler an den Inhalt kommen sollen, sondern es handelt sich ausschließlich im Deko. Platziert man nun jedoch an einem Block einen solchen Rahmen, kann der Spieler zwar nicht den Block dahinter abbauen, da dieser ja durch das Spiel geschützt ist, aber er kann bspw. einen Block Sandstein direkt davor platzieren, sodass der Rahmen zerstört wird und dieser inklusive Inhalt droppt. Das ist nicht gut so und wäre schön, wenn das behoben werden kann - bspw. indem man keinen Block in das Feld des Rahmens setzen darf… Besten Dank und viele Grüße :)

### LINKED ISSUE #239: Stopped game only bw.setup join
Wenn ein BW Game gestoppt ist, (aus welchem grund auch immer) sollten nur Spieler mit der bw.setup permission joinen können.

### LINKED ISSUE #275: Tabliste
Die Zuschauer werden in der Tabliste nicht aktualisiert.

Die Zuschauer können sich untereinander in der Tabliste sehen. Aber du siehst nicht die die nach einem joinen, sonder nur die davor.

### LINKED ISSUE #335: /bw removeteam it does not work bug
it is true that because the team has been removed. but it is not removed !!

### LINKED ISSUE #369: [Feature] [Bungeecord] Endgame to Gamelobby
Add configuration option to teleport players to game lobby (waiting lobby) while endgame running - instead of staying on the bedwars map.

### LINKED ISSUE #384: [BUG (?)] Multiple players joining quickly -> Invisible to each other
Might be a bug or not. I am investigating but need feedback from other users if they are experiencing the same issue:
When using a party system and the party leader joins the game lobby, of course, all the other players are getting teleported into the game, too. BUT: It seems like BedwarsRel then messes up visibility of players. Some of the players can't see each other in the game lobby (even in tablist) and then they aren't visible in game as well.
Steps to reproduce (if you don't have a party system): Use /send command from Bungeecord to send a bunch of people (maybe current server) to one of your game servers.
Need feedback: Is the same happening on your servers?

### PR DESCRIPTION
**Pull request by sebastianbinder**
Build http://ci.sebastianbinder.com/job/Bedwars-Rel/24/artifact/dist/BedwarsRel-1.2.8-56411ebd47ee638879539b6b4ff3cba6f88c79d8.jar is based on this branch. So everything can be tested again before final merge. As long as there aren't any major bugs coming up now, this branch is ready to be merged into master branch. This shall be the final 1.2.8 release - any other bugs should be fixed in upcoming version 1.2.9 then.

fixes #233
fixes #239 
fixes #275
fixes #335 
fixes #369 
fixes #384 

@Yannici @Granik24 @Block-Build - is that okay for all of you?

### CODE REVIEW

**Comment by sebastianbinder** [comment]
Feedback from @Granik24 
> Players who are getting killed from void, respawn in lobby

:/ why is everything so different on every server :/

**Comment by Yannici** [comment]
> Players who are getting killed from void, respawn in lobby

Maybe something to do with your feature with game-ending in lobby or something? ^^

**Comment by sebastianbinder** [comment]
> Maybe something to do with your feature with game-ending in lobby or something? ^^

Granik has already been using this new feature before - so it shouldn't be responsible for that. I rather think that all these issues are caused by the "runTaskLater" things I implemented. One server is slower, the other one is faster - one player connection is slower, the other one is faster - and so on…. I'll do some code rewriting again today...

**Comment by Granik24** [comment]
@sebastianbinder seems like, it's okay. :) Everything should works great.

**Comment by sebastianbinder** [comment]
@Yannici - could you also have a look on the code and merge it if you are happy with it? :)

**Comment by Yannici** [comment]
I will, yes.

**Comment by Yannici** [comment]
I will merge this later this day and will create new update on spigot/bukkit :) thanks for your help @sebastianbinder

**Comment by sebastianbinder** [comment]
@Yannici - any news for me? Wanna start with the new version, but would like to have the proper release beforehand :)

**Comment by Yannici** [comment]
@sebastianbinder Could you please put together the final changes? Which bugfixes, which new features etc.? So I can easily create the new update description. For me it's a little bit hard to get every change together in the update description.

**Comment by sebastianbinder** [comment]
@Yannici - already did that :)
Can you see this draft? https://github.com/Yannici/bedwars-reloaded/releases/tag/untagged-38eb62de7976ec0bdbcb

**Pull request merged**
