### PR TITLE
Add possibility to break every block. #393

### PR DESCRIPTION
**Pull request by Block-Build**
Issue #393 
Add in config like this:

```javascript
breakable-blocks:
- all
```

### CODE REVIEW

**Comment by sebastianbinder** [comment]
Actually I don't like that way. I'd rather prefer a way like a config value ``break-blocks: false`` or ``break-blocks: true`` and then a list like ``break-blocks-excemptions:`` which corresponds to our current ``breakable-blocks:`` list and makes blocks breakable when ``break-blocks: false`` or unbreakable when ``break-blocks: true``.

**Comment by Yannici** [comment]
Even the implementation isn't pretty well :/

**Comment by sebastianbinder** [comment]
@Yannici: how would you like to see the config? One of our proposals or any other idea to display that use case in a config file?

**Comment by sebastianbinder** [comment]
not sure if this one works with ``yml`` - but this might be a cleaner combination if possible...
```yml
blocks-breakable: true
  exceptions:
  - dirt
  - glass
```

**Comment by sebastianbinder** [comment]
Mm. Of course this is as always something you we could discuss about for ages. In my opinion my last config idea doesn't activate any "blacklist". It just gives the possibility to say if blocks should be breakable or not - and gives you the possibility to specify any exceptions from that config value. But I don't know which one is better :/

I think we really need a final decision of our neutral @Yannici here ;)

**Comment by Yannici** [comment]
I think @Block-Build's solution is a little bit more clearly. If `use-as-blacklist` is false, everyone knows it's a whitelist then ;) In your solution @sebastianbinder, someone could think the list will be ignored when breakable-blocks is set to false.

**Comment by sebastianbinder** [comment]
Okay. Then we have a decision :)
@Block-Build can you update your Pull Request?

**Comment by sebastianbinder** [comment]
"Yes, I can!" xD

**Pull request closed without merging**
