### PR TITLE
[1.2.8] Add compass as player tracker

### LINKED ISSUE #354: [Request] Compass showing direction of closest enemy
Feature: Compass showing direction of closest enemy

### PR DESCRIPTION
**Pull request by sebastianbinder**
resolves #354 
locally tested, build on jenkins succeeded, tests in production on my server worked fine.

### CODE REVIEW

**Comment by Granik24** [comment]
Tested on our network, works great. :+1:  :)

**Comment by sebastianbinder** [comment]
Thank you @Granik24 :) Let's see if @Yannici is gonna accept the pull request :)

**Comment by Yannici** [comment]
Of course I will add this wonderful feature ;) Love it.

**Comment by sebastianbinder** [comment]
Yes! :)

**Pull request merged**
