### PR TITLE
[1.2.8-p1] Fix Player Spawn Location if not Bungeecord

### LINKED ISSUE #432: Schild und Spawn
Wenn ich ein Schild erstellen mit

Shild:

[bw]
was

steht da "Spiel kann nich gefunden" und wenn man /bw join was eingibt an ist man in der lobby.

Spawn:

wenn ich jemanden töte oder er Feld aus der welt landet er am welt spawn wenn ich aber /kill eingebe ladet er am team spawn

ich bitte um Hilfe

### PR DESCRIPTION
**Pull request by sebastianbinder**
Fixes issues concerning player joining server and player joining game if not on Bungeecord.
Should fix #432 and #433 
Build for testing: http://ci.sebastianbinder.com/job/Bedwars-Rel/34/artifact/dist/BedwarsRel-1.2.8-82417b96ede8897b1039d6109b2cc7a2c505819c.jar

### CODE REVIEW

**Comment by Yannici** [comment]
And please, test non-bungeecord better! This is as important as the bungeecord mode ...

**Comment by sebastianbinder** [comment]
For sure :) And would be great if @Granik24 and @Block-Build could each set up a single non-bungeecord spigot server for testing as well :P

**Comment by Yannici** [comment]
Can we merge this? I want to release a fixed version asap because I want prevent that the wrong 1.2.8 will spread ;)

**Comment by sebastianbinder** [comment]
@Yannici  -  It's your decision :)
In my opinion it should work. So for sure, this patch is better than the release. But I was the only person testing this so far, so I don't know if there are still any issues left… So if you don't mind publishing another patch if there is any other issue coming up, then merge it.

**Comment by sebastianbinder** [comment]
Just did some more testing with one of my Mods - everything seems to be fine.

**Comment by Granik24** [comment]
@sebastianbinder Going to test it right now.

**Pull request merged**
